drop table if exists books, clients, telephones, washing_machines, cart, cart_items;

create table if not exists books
(
    id           bigint generated by default as identity not null,
    author       varchar(255)                            not null,
    product_type varchar(255)                            not null,
    cost         integer                                 not null,
    name         varchar(255)                            not null,
    constraint pk_book primary key (id)
);

create table if not exists clients
(
    id       bigint generated by default as identity not null,
    name     varchar(255)                            not null,
    email    varchar(255)                            not null,
    login    varchar(255)                            not null,
    password varchar(255)                            not null,
    constraint pk_client primary key (id)
);

create table if not exists telephones
(
    id             bigint generated by default as identity not null,
    creator        varchar(255)                            not null,
    battery_volume integer                                 not null,
    seller_id      integer                                 not null,
    product_type   varchar(255)                            not null,
    cost           integer                                 not null,
    name           varchar(255)                            not null,
    constraint pk_telephones primary key (id)
);

create table if not exists washing_machines
(
    id           bigint generated by default as identity not null,
    seller_id    integer                                 not null,
    tank_volume  integer                                 not null,
    product_type varchar(255)                            not null,
    cost         integer                                 not null,
    name         varchar(255)                            not null,
    constraint pk_washing_machines primary key (id)
);

CREATE TABLE IF NOT EXISTS cart
(
    id bigint NOT NULL,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cart_items
(
    id                bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cart_id           bigint                                              NOT NULL,
    cart_item_id      bigint                                              NOT NULL,
    cart_item_type    character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cart_item_name    character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cart_items_amount integer                                             NOT NULL,
    CONSTRAINT pk_cart_item PRIMARY KEY (id),
    CONSTRAINT fk_cart_id FOREIGN KEY (cart_id) REFERENCES cart (id)
);

